apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://cloud-config:9296"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/product_db"
  SPRING_DATASOURCE_USERNAME: "ecommerce"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
